server:
  port: 8082   # unique port for login-service

spring:
  application:
    name: login-service   # service name for Eureka

  datasource:
    url: jdbc:mysql://localhost:3306/trading_application
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Eureka server address
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: 7fbbf50c9a72d3a8a61efcb4d5b29c7e41f2f8b9c0e3d19f6a7c8b5e29a4d6f3f8e2c7d1a4b9e0f2c6d3a8e5f9b1c7d2e4   # use a strong secret in real world
  expiration: 3600000   # 1 hour (in ms)
